# Makefile
# See https://docs.cocotb.org/en/stable/quickstart.html for more info
 
# defaults
SIM ?= icarus
FST ?= -fst # Use more efficient FST format
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
 
# Real design sources, in dependency order (tinygpu_pkg.sv must come
# first -- other files `include it; everything else is order-independent
# but kept in a sensible bottom-up order for readability).
PROJECT_SOURCES = \
	tinygpu_pkg.sv \
	scratchpad.sv \
	bus_interconnect.sv \
	accel_regs.sv \
	vector_accel.sv \
	rv32_core.sv \
	debug_regs.sv \
	ext_loader.sv \
	tinygpu_soc.sv \
	tt_um_tinygpu_rv32.sv
 
ifneq ($(GATES),yes)
# RTL simulation:
SIM_BUILD				= sim_build/rtl
VERILOG_SOURCES += $(addprefix $(SRC_DIR)/,$(PROJECT_SOURCES))
else
# Gate level simulation:
SIM_BUILD				= sim_build/gl
COMPILE_ARGS    += -DGL_TEST
COMPILE_ARGS    += -DFUNCTIONAL
COMPILE_ARGS    += -DUSE_POWER_PINS
COMPILE_ARGS    += -DSIM
COMPILE_ARGS    += -DUNIT_DELAY=\#1
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/primitives.v
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v
# this gets copied in by the GDS action workflow
VERILOG_SOURCES += $(PWD)/gate_level_netlist.v
endif
 
# Allow sharing configuration between design and testbench via `include`:
COMPILE_ARGS 		+= -I$(SRC_DIR)
 
# Include the testbench sources:
VERILOG_SOURCES += $(PWD)/tb.v
TOPLEVEL = tb
 
# List test modules to run, separated by commas and without the .py suffix:
COCOTB_TEST_MODULES = test
 
# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
